version: '3'
services:
  selenium:
    image: selenium/standalone-firefox
    ports:
      - "4444:4444"
    networks:
      main:
        ipv4_address: 172.31.16.2
  app:
    image: 975050213689.dkr.ecr.us-east-2.amazonaws.com/my-app 
    depends_on: 
      - selenium
    networks:
      main:
        ipv4_address: 172.31.16.3

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "172.31.16.0/20"
