services:
  selenium:
      image: selenium/standalone-firefox
      ports:
        - "4444:4444"
      restart: always
      networks:
        main:
          ipv4_address: 10.0.0.2
  app:
      image: my-app
      depends_on: 
        - selenium
      restart: always
      networks:
        main:
          ipv4_address: 10.0.0.3

networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"
