apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ilyassakhanov/my-app
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: cfg
            mountPath: /cfg
            readOnly: true
      volumes:
      - name: cfg
        secret:
          secretName: my-app-credentials
