apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ilyassakhanov/my-app
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: creds
            mountPath: /creds
            readOnly: true
          - name: config
            mountPath: /config
            readOnly: true 
          - mountPath: /app/data
            name: my-app-data
      volumes:
      - name: creds
        secret:
          secretName: my-app-credentials
      - name: config
        configMap:
          name: my-app-config
      - name: my-app-data
        persistentVolumeClaim:
          claimName: my-app-storage

