apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-webdriver
spec:
  selector:
    matchLabels:
      app: selenium
  replicas: 1 
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
      - name: selenium-firefox
        image: selenium/standalone-firefox
        ports:
        - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  selector:
    app: selenium
  ports:
  - protocol: TCP
    port: 4444
    targetPort: 4444