apiVersion: v2
name: electro
description: A helm chart to deploy Telegram bot Electro for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

# This sets a minimal Kubernetes version
kubeVersion: ">=1.24.0-0"
# Electro bot uses selenium for parsing data
sources: 
  - https://github.com/ilyassakhanov/Electro-bot
maintainers:
  - name: Ilyas Sakhanov
    email: ilyas.sakhanov@gmail.com
annotations:
  documentation: https://github.com/ilyassakhanov/Electro-bot/blob/main/README.md