# Default values for electro.

replicaCount: 1

image:
  repository: ilyassakhanov/my-app 
  # This sets the pull policy for images.
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1767466436"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    memory: "256Mi"
    cpu: "250m"
  requests:
    memory: "128Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}

selenium:
  replicaCount: 1
  image:
    repository: selenium/standalone-firefox
    tag: "latest"
  service:
    port: 4444
    name: selenium
  resources:
    limits:
      memory: "1024Mi"
      cpu: "400m"
    requests:
      memory: "256Mi"
      cpu: "100m"

secretName: my-app-credentials
configMapName: my-app-config

pvc:
  claimName: my-app-storage
  accessMode: ReadWriteOncePod
  storage: 5Mi

config:
  botname: PREelectro_bot
