apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  login: <path:secret/data/electro#login>
  password: <path:secret/data/electro#password>
  apikey: <path:secret/data/electro#apikey>
  users: <path:secret/data/electro#users>
