apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-app.selenium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-app.selenium.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "my-app.selenium.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.selenium.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        {{- include "my-app.selenium.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: selenium-firefox
        image: "{{ .Values.selenium.image.repository }}:{{ .Values.selenium.image.tag }}"
        resources:
          {{- toYaml .Values.selenium.resources | nindent 10 }}
        ports:
        - containerPort: {{ .Values.selenium.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.selenium.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-app.selenium.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "my-app.selenium.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.selenium.service.port }}
    targetPort: {{ .Values.selenium.service.port }}
