name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --platform linux/arm64 containers/  --tag ilyassakhanov/my-app:$(date +%s)
