name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

      # Setting multiplatform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

      # Log into Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate timestamp
      id: ts
      run: echo "TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

    # Build and push
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: containers/               
        platforms: linux/amd64,linux/arm64
        push: true 
        tags: |
            ilyassakhanov/my-app:latest
            ilyassakhanov/my-app:${{ env.TIMESTAMP }}